"""PostgreSQL schema for classroom persistence, mirrored table-for-table
from the SQLite schema in ``_storage.py``.

Applied through a versioned migration list rather than a single
``CREATE TABLE IF NOT EXISTS`` script, because two Postgres workers racing
to create the same table concurrently can still hit a duplicate-object
error under MVCC - ``_storage.ensure_postgres_schema`` serializes this with
a Postgres advisory lock so it is safe for concurrent startup.

Design choices kept deliberately close to the SQLite schema so the rest of
``db.py`` needs no backend-specific branches:

- Booleans (``is_assessment``, ``locked``, ``completed``) stay ``INTEGER``
  0/1, not native ``BOOLEAN`` - the existing ``bool(row.get(...))`` decoding
  in db.py then works unchanged for both backends.
- Surrogate keys use ``GENERATED BY DEFAULT AS IDENTITY`` (the modern
  replacement for ``SERIAL``) instead of SQLite's
  ``INTEGER PRIMARY KEY AUTOINCREMENT``. "BY DEFAULT" (rather than
  "ALWAYS") matters: the sqlite-to-postgres migration tool inserts
  explicit historical IDs, which "ALWAYS" would reject.
- Case-insensitive ordering in db.py uses ``LOWER(col)`` rather than
  SQLite's ``ORDER BY col COLLATE NOCASE``, since ``LOWER()`` works
  identically on both engines.
- ``ON CONFLICT ... DO UPDATE`` upserts already used in db.py
  (onboarding_progress, learner_notification_state) are native PostgreSQL
  syntax that SQLite borrowed, so they need no changes at all.

To add a future migration: append a new ``(N, [...])`` tuple with N one
higher than the current max. Never edit or remove a tuple that has already
shipped - a fresh database and an upgraded one must reach the same schema
by replaying the same numbered steps.
"""

from __future__ import annotations

from typing import List, Tuple

MIGRATIONS: List[Tuple[int, List[str]]] = [
    (
        1,
        [
            """
            CREATE TABLE instructors (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                display_name TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE cohorts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                instructor_id INTEGER NOT NULL REFERENCES instructors(id),
                name TEXT NOT NULL,
                join_code TEXT UNIQUE NOT NULL,
                status TEXT NOT NULL DEFAULT 'active',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE learners (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cohort_id INTEGER NOT NULL REFERENCES cohorts(id),
                display_name TEXT NOT NULL,
                token TEXT UNIQUE NOT NULL,
                joined_at TEXT NOT NULL,
                last_active_at TEXT
            )
            """,
            """
            CREATE TABLE assignments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cohort_id INTEGER NOT NULL REFERENCES cohorts(id),
                title TEXT NOT NULL,
                instructions TEXT NOT NULL DEFAULT '',
                starter_code TEXT NOT NULL DEFAULT '',
                due_date TEXT,
                expected_concepts TEXT NOT NULL DEFAULT '[]',
                ai_policy TEXT NOT NULL DEFAULT 'FULL',
                capability_settings TEXT,
                is_assessment INTEGER NOT NULL DEFAULT 0,
                start_at TEXT,
                end_at TEXT,
                locked INTEGER NOT NULL DEFAULT 0,
                status TEXT NOT NULL DEFAULT 'draft',
                published_at TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE assignment_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assignment_id INTEGER NOT NULL REFERENCES assignments(id),
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                status TEXT NOT NULL DEFAULT 'not_started',
                code TEXT NOT NULL DEFAULT '',
                submitted_code TEXT,
                run_count INTEGER NOT NULL DEFAULT 0,
                success_run_count INTEGER NOT NULL DEFAULT 0,
                last_error TEXT,
                last_saved_at TEXT,
                submitted_at TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE(assignment_id, learner_id)
            )
            """,
            """
            CREATE TABLE help_requests (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cohort_id INTEGER NOT NULL REFERENCES cohorts(id),
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                assignment_id INTEGER REFERENCES assignments(id),
                message TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'open',
                note TEXT,
                created_at TEXT NOT NULL,
                resolved_at TEXT
            )
            """,
            """
            CREATE TABLE curriculum_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL UNIQUE REFERENCES learners(id),
                course_id TEXT NOT NULL DEFAULT 'python_foundations',
                current_module_id TEXT,
                current_stage TEXT,
                started_at TEXT,
                last_activity_at TEXT
            )
            """,
            """
            CREATE TABLE module_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                module_id TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'not_started',
                completed_stages TEXT NOT NULL DEFAULT '[]',
                attempts INTEGER NOT NULL DEFAULT 0,
                quiz_score INTEGER,
                quiz_total INTEGER,
                completed_at TEXT,
                updated_at TEXT NOT NULL,
                UNIQUE(learner_id, module_id)
            )
            """,
            """
            CREATE TABLE custom_lessons (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cohort_id INTEGER NOT NULL REFERENCES cohorts(id),
                instructor_id INTEGER NOT NULL REFERENCES instructors(id),
                title TEXT NOT NULL,
                objective TEXT NOT NULL DEFAULT '',
                explanation TEXT NOT NULL DEFAULT '',
                starter_code TEXT NOT NULL DEFAULT '',
                instructions TEXT NOT NULL DEFAULT '',
                expected_concepts TEXT NOT NULL DEFAULT '[]',
                challenge TEXT NOT NULL DEFAULT '',
                expected_output TEXT,
                quiz_question TEXT,
                quiz_choices TEXT NOT NULL DEFAULT '[]',
                quiz_answer_index INTEGER,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE custom_projects (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cohort_id INTEGER NOT NULL REFERENCES cohorts(id),
                instructor_id INTEGER NOT NULL REFERENCES instructors(id),
                title TEXT NOT NULL,
                instructions TEXT NOT NULL DEFAULT '',
                starter_code TEXT NOT NULL DEFAULT '',
                expected_concepts TEXT NOT NULL DEFAULT '[]',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE custom_project_checkpoints (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL REFERENCES custom_projects(id),
                order_index INTEGER NOT NULL DEFAULT 0,
                label TEXT NOT NULL,
                check_type TEXT NOT NULL,
                check_config TEXT NOT NULL DEFAULT '{}'
            )
            """,
            """
            CREATE TABLE onboarding_progress (
                learner_id INTEGER PRIMARY KEY REFERENCES learners(id),
                completed INTEGER NOT NULL DEFAULT 0,
                completed_at TEXT
            )
            """,
            """
            CREATE TABLE learner_notification_state (
                learner_id INTEGER PRIMARY KEY REFERENCES learners(id),
                assignments_seen_at TEXT,
                ide_orientation_at TEXT
            )
            """,
            """
            CREATE TABLE lesson_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                lesson_id TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'not_started',
                attempts INTEGER NOT NULL DEFAULT 0,
                last_code TEXT,
                updated_at TEXT NOT NULL,
                UNIQUE(learner_id, lesson_id)
            )
            """,
            """
            CREATE TABLE project_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                project_id TEXT NOT NULL,
                checkpoints_completed TEXT NOT NULL DEFAULT '[]',
                code TEXT,
                active_file TEXT,
                files TEXT,
                updated_at TEXT NOT NULL,
                UNIQUE(learner_id, project_id)
            )
            """,
            """
            CREATE TABLE concept_progress (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                concept TEXT NOT NULL,
                state TEXT NOT NULL DEFAULT 'not_started',
                evidence_count INTEGER NOT NULL DEFAULT 0,
                last_evidence_at TEXT,
                UNIQUE(learner_id, concept)
            )
            """,
            """
            CREATE TABLE progress_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                learner_id INTEGER NOT NULL REFERENCES learners(id),
                cohort_id INTEGER,
                kind TEXT NOT NULL,
                payload TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL
            )
            """,
            "CREATE INDEX idx_learners_cohort ON learners(cohort_id)",
            "CREATE INDEX idx_assignments_cohort ON assignments(cohort_id)",
            "CREATE INDEX idx_progress_events_learner ON progress_events(learner_id)",
            "CREATE INDEX idx_progress_events_cohort ON progress_events(cohort_id, created_at)",
            "CREATE INDEX idx_help_requests_cohort ON help_requests(cohort_id, status)",
            "CREATE INDEX idx_module_progress_learner ON module_progress(learner_id)",
            "CREATE INDEX idx_custom_lessons_cohort ON custom_lessons(cohort_id)",
            "CREATE INDEX idx_custom_projects_cohort ON custom_projects(cohort_id)",
            "CREATE INDEX idx_custom_project_checkpoints_project ON custom_project_checkpoints(project_id)",
        ],
    ),
]
